version: '3.8'

services:
  # API service
  api:
    build: .
    command: uvicorn presentation.api.fastapi_app:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://admin:securepassword@postgres:5432/sephora_csat
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - postgres
      - redis
      - elasticsearch

  # Scraping worker
  scraper:
    build: .
    command: python -m scrapers.run_scrapers
    volumes:
      - ./data:/app/data
    environment:
      - TRUSTPILOT_API_KEY=${TRUSTPILOT_API_KEY}
      - TWITTER_BEARER_TOKEN=${TWITTER_BEARER_TOKEN}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    depends_on:
      - postgres
      - redis
      - elasticsearch

  # PostgreSQL database
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: sephora_csat
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: securepassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./infrastructure/database/postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  # Redis cache
  redis:
    image: redis:6
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # Elasticsearch for text search
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.0
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - ELASTIC_PASSWORD=securepassword
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

volumes:
  postgres_data:
  redis_data:
  elasticsearch_data:
