version: '3.8'
services:
  api:
    image: ghcr.io/${{ github.repository }}:latest
    command: uvicorn presentation.api.fastapi_app:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    environment:
      - ENV=staging
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - app-network

  dashboard:
    image: ghcr.io/${{ github.repository }}:latest
    command: streamlit run presentation/dash/streamlit_app.py --server.port 8501
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://api:8000
      - ENV=staging
    depends_on:
      - api
    networks:
      - app-network

  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    ports:
      - "5000:5000"
    volumes:
      - mlflow-artifacts:/mlflow
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - MLFLOW_ARTIFACT_ROOT=/mlflow
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mlflow-artifacts:
